// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmrgegqtgacicfispise.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcmdlZ3F0Z2FjaWNmaXNwaXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxNzQ1MjcsImV4cCI6MjA1Mjc1MDUyN30.yVLMQy9pQki-STbd3_f-a8NMWYSkRZZvCx4xigIjiPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);